# Generated by Django 4.2 on 2024-01-08 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_tags_project_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technology',
        ),
    ]
