# Generated by Django 4.2 on 2024-01-08 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_photo_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
